-- CREATE TABLE IF NOT EXISTS products (
--     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--
--     name VARCHAR(255) NOT NULL,
--     category VARCHAR(255) NOT NULL,
--     barcode VARCHAR(64) UNIQUE NOT NULL,
--
--     purchase_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
--     selling_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
--
--     unit VARCHAR(20) NOT NULL CHECK (unit IN ('piece', 'weight')),
--
--     stock NUMERIC(12, 3) NOT NULL DEFAULT 0,
--     min_stock NUMERIC(12, 3) NOT NULL DEFAULT 10,
--
--     image TEXT NOT NULL DEFAULT 'https://i.pinimg.com/736x/11/6a/2b/116a2b68ea33003c15614ca669a22a25.jpg',
--
--     created_at TIMESTAMP NOT NULL DEFAULT NOW(),
--     updated_at TIMESTAMP NOT NULL DEFAULT NOW()
-- );
--
-- CREATE TABLE IF NOT EXISTS receipts (
--     id BIGSERIAL PRIMARY KEY,
--
--     receipt_number VARCHAR(64) NOT NULL UNIQUE,
--     created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--
--     payment_method VARCHAR(20) NOT NULL CHECK (payment_method IN ('card', 'cash')),
--     payment_label VARCHAR(50) NOT NULL,
--
--     total NUMERIC(12, 2) NOT NULL CHECK (total >= 0),
--     received_amount NUMERIC(12, 2),
--     change_amount NUMERIC(12, 2),
--
--     -- Все позиции чека храним внутри JSONB
--     -- Пример: [{ productId, name, barcode, quantity, price, total }]
--     items JSONB NOT NULL DEFAULT '[]'::jsonb
-- );
--
-- CREATE INDEX IF NOT EXISTS idx_receipts_created_at
--     ON receipts(created_at DESC);
--
-- CREATE INDEX IF NOT EXISTS idx_receipts_payment_method
--     ON receipts(payment_method);
--
-- CREATE INDEX IF NOT EXISTS idx_receipts_items
--     ON receipts USING GIN (items);

CREATE TABLE IF NOT EXISTS receipts (
    id BIGSERIAL PRIMARY KEY,

    receipt_number VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    payment_method VARCHAR(20) NOT NULL CHECK (payment_method IN ('card', 'cash')),
    payment_label VARCHAR(50) NOT NULL,

    total NUMERIC(12, 2) NOT NULL CHECK (total >= 0),
    received_amount NUMERIC(12, 2),
    change_amount NUMERIC(12, 2),

    items JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_receipts_created_at
    ON receipts(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_receipts_payment_method
    ON receipts(payment_method);

CREATE INDEX IF NOT EXISTS idx_receipts_items
    ON receipts USING GIN (items);